spring:
  application:
    name: DevLinks
  datasource:
    driver-class-name: org.oracle.jdbc.Driver
    url: jdbc:oracle:thin:@192.168.0.11:1521:jvn1orcl
    username: {SPRING_DATASOURCE_USERNAME}
    password: {SPRING_DATASOURCE_PASSWORD}

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none

    show-sql: false
    properties:
      hibernate:
        format_sql: true


devLinks:
  jwt:
    secret: ${SPRING_JWT_SECRET_KEY}

server:
  port: 8080
#  address: ...


#mybatis:
#  configuration:
#    map-underscore-to-camel-case: true
#  mapper-locations: mappers/*Mapper.xml
#  type-aliases-package: com.jvn1o.devlinks.entity
#logging:
#  level:
#    com.jvn1o.devlinks.repository.LinkRepository: trace