# application.yml (공통 설정)
spring:
  application:
    name: DevLinks  # 앱 이름

  datasource:
    driver-class-name: oracle.jdbc.OracleDriver  # 공통 드라이버 클래스명 설정

  jpa:
    hibernate:
      ddl-auto: validate  # ddl-auto 옵션은 공통으로 validate
    show-sql: true  # SQL 쿼리 출력 설정 (개발 편의)
    properties:
      hibernate:
        format_sql: true  # SQL 포맷팅 옵션

  servlet:
    multipart:
      enabled: true  # 멀티파트 업로드 사용 설정
      max-file-size: 500MB  # 업로드 최대 파일 크기
      max-request-size: 1024MB  # 최대 요청 크기

  web:
    resources:
      static-locations: file:./uploads/  # 정적 자원 위치

server:
  port: 8080  # 서버 포트 번호

file:
  upload-dir: ./uploads  # 파일 업로드 기본 경로

# 임시 H2 설정 (필요시 활성화)
#spring:
#  datasource:
#    url: jdbc:h2:mem:testdb
#    driver-class-name: org.h2.Driver
#    username: sa
#    password:
#  jpa:
#    hibernate:
#      ddl-auto: update
#    database-platform: org.hibernate.dialect.H2Dialect